stages:
  - setup
  - build
  - test

.default_template: &default_template
  tags:
    - windows-shell
  image: mcr.microsoft.com/dotnet/sdk:9.0.300

setup:
  <<: *default_template
  stage: setup
  script:
    - echo "Setup complete..."
    - powershell -Command Write-Host $(dotnet --version)

build:
  <<: *default_template
  stage: build
  script:
    - echo "Restoring dependencies..."
    - dotnet restore

    - echo "Building solution..."
    - dotnet build --no-restore -f net8.0-windows --configuration $BUILD_CONFIGURATION

test:
  <<: *default_template
  stage: test
  dependencies:
    - build
  before_script:
    - echo "Starting WinAppDriver..."
    - Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
  script:
    - echo "Running unit tests..."
    - |
      if ("$ENABLE_CODE_COVERAGE" -eq "true")
      {
         dotnet test --no-build -f net8.0-windows --configuration $BUILD_CONFIGURATION --collect:"XPlat Code Coverage"
      }
      else {
        dotnet test --no-build -f net8.0-windows --configuration $BUILD_CONFIGURATION
      }
